# Generated by Django 4.0.10 on 2024-03-31 16:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('django_deovi', '0002_alter_directory_options_alter_mediafile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='last_update',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='The last update date for this device.', verbose_name='last update'),
        ),
    ]
