# Generated by Django 4.0.10 on 2024-04-28 13:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_deovi', '0003_device_last_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='disk_free',
            field=models.BigIntegerField(default=0, help_text='Free space size on disk of which the device belong to. This will becomputed from the device size and everything else that belong onto the same disk.', validators=[django.core.validators.MinValueValidator(0)], verbose_name='disk free'),
        ),
        migrations.AddField(
            model_name='device',
            name='disk_total',
            field=models.BigIntegerField(default=0, help_text='Total available disk size of which the device belong to.', validators=[django.core.validators.MinValueValidator(0)], verbose_name='disk total'),
        ),
        migrations.AddField(
            model_name='device',
            name='disk_used',
            field=models.BigIntegerField(default=0, help_text='Total used disk size of which the device belong to. This will includesthe device size and everything else that belong onto the same disk.', validators=[django.core.validators.MinValueValidator(0)], verbose_name='disk usage'),
        ),
    ]
