{% comment %}
Here are gathered the common variables we could use in shell scripts
{% endcomment %}
PROJECTDIR="{{ settings.BASE_DIR }}"
STATICDIR="{{ settings.STATIC_ROOT }}"
MEDIADIR="{{ settings.MEDIA_ROOT }}"
DEPLOY_BUILDDIR="{{ settings.DEPLOYMENT_BUILD_DESTINATION }}"
DEPLOY_LOGSDIR="{{ settings.DEPLOYMENT_LOGS_DIRPATH }}"
DEPLOY_USER="{{ settings.DEPLOYMENT_USER }}"
DEPLOY_GROUP="{{ settings.DEPLOYMENT_GROUP }}"
DEPLOY_HTTPSERVER_PORT="{{ settings.DEPLOYMENT_HTTPSERVER_PORT }}"
DEPLOY_APPSERVER_BINDING="{{ APPSERVER_BINDING }}"
DEPLOY_APPSERVER_BINDING_INTERFACE="{{ APPSERVER_BINDING_INTERFACE }}"
DEPLOY_SOCKET_FILEPATH="{{ SOCKET_FILEPATH }}"

SETTINGS_MODULE=sandbox.settings.production
DJANGO_WSGI_MODULE=wsgi
APPNAME="{{ settings.DEPLOYMENT_APPNAME }}"

PYTHON_BIN="$PROJECTDIR/.venv/bin/python"
MANAGE_SCRIPT="$PYTHON_BIN ./manage.py"

NGINX_CONFIG_FILENAME="010_$APPNAME"
GUNICORN_SERVICE_FILENAME="gunicorn_$APPNAME.service"
GUNICORN_SOCKET_FILENAME="gunicorn_$APPNAME.socket"
SEARCH_INDEX="{{ SEARCH_INDEX }}"
