#!/bin/bash

# Name of the application
NAME="{{ settings.DEPLOYMENT_APPNAME }}"
# Base directory for project
BASE_DIRECTORY={{ settings.BASE_DIR }}
# Django project directory
GUNICORN_BIN=$BASE_DIRECTORY/.venv/bin/gunicorn
# Django project directory
DJANGODIR=$BASE_DIRECTORY/sandbox
# We will communicate using this unix socket
SOCKFILE=$BASE_DIRECTORY/run/gunicorn.sock
# The user to run as (use username from current session)
USER=$USER
# The group to run as (assume it is the same name as username)
GROUP=$USER
# How many worker processes should Gunicorn spawn
NUM_WORKERS=3
# Which Django settings file to use
DJANGO_SETTINGS_MODULE=sandbox.settings.production
# WSGI module name
DJANGO_WSGI_MODULE=sandbox.wsgi

echo "Starting $NAME as `whoami`";

# Activate the virtual environment
cd $DJANGODIR;
export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE;
export PYTHONPATH=$DJANGODIR:$PYTHONPATH;

# Create the run directory if it doesn't exist
RUNDIR=$(dirname $SOCKFILE)
test -d $RUNDIR || mkdir -p $RUNDIR;

# Start your Django Unicorn
# Programs meant to be run under supervisor should not daemonize themselves (do not use --daemon)
exec $GUNICORN_BIN ${DJANGO_WSGI_MODULE}:application \
--name $NAME \
--workers $NUM_WORKERS \
--user=$USER --group=$GROUP \
--bind=unix:$SOCKFILE \
--log-level=debug \
--log-file=-
