server {
    listen {{ settings.DEPLOYMENT_HTTPSERVER_PORT }};

    server_name _;
    client_max_body_size 5M;
    access_log {{ settings.DEPLOYMENT_LOGS_DIRPATH }}/nginx-access.log;
    error_log {{ settings.DEPLOYMENT_LOGS_DIRPATH }}/nginx-error.log;

    location = /favicon.ico { access_log off; log_not_found off; }

    location {{ settings.STATIC_URL }} {
        alias {{ settings.STATIC_ROOT }}/;
    }

    location {{ settings.MEDIA_URL }} {
        alias {{ settings.MEDIA_ROOT }}/;
    }

    location / {
        include proxy_params;
        proxy_pass http://{{ APPSERVER_BINDING_INTERFACE }};
    }
}
